<?php
// $Id$

/** 
* Implements hook_help()
*/
function remote_block_help($path, $arg) {
  $output = '';
  switch($path) {
    case 'admin/help#remote_block':
    $output = '<p>' . t('Remote Block renders blocks on a regionless page so that they may be embedded via an iframe. You may use the following syntax (--add syntax here--) to embed any given block on a site. Note that required CSS and JS will be included, so blocks with special styles and behaviors (such as Quicktabs blocks) will still function.') . '</p>';
    $output .= '<p>' . t('The pages provided by Remote Block can also display bare HTML if the ?theme=none query string is appended to the URL. This is useful when using wget to grab raw HTML for use in external sites.') . '</p>';
    break;
    }
  return $output;
}

/**
 * Implements hook_menu().
 */
function remote_block_menu() {
  $items = array();

  $items['remote-block/%/%/%'] = array(
    'page callback' => 'remote_block_embed',
    'page arguments' => array(1, 2, 3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Menu callback for remote-block/%/%/% -
 * invokes the block view hook in order to render a certain block.
 */
function remote_block_embed($format, $module, $delta) {
  // Sets the variable to print without CSS and JS based on query string.
  $theme = TRUE;
  if(isset($_GET) && isset($_GET['theme']) && $_GET['theme'] == 'none') { $theme = FALSE; }

  // Loads the block content, or returns error if failure.
  if(isset($module) && module_exists($module) && isset($delta)) {
	  $block = module_invoke($module, 'block', 'view', $delta);
	}
	else {
	  print 'Invalid request.';
	}

  // Sets up the variables of $css, $content, and $js.
  $css = drupal_get_css();
  // Includes Quicktabs CSS if necessary.
  if($module == 'quicktabs') { 
    $css .= 
      '<style type="text/css">
         .quicktabs-hide {
          display: block;
          position: absolute;
          left: -10000px;
          top: -10000px;
         }
       </style>';
  }
  $content = $block['content'];
  // Adds JS at the bottom.
  $js = drupal_get_js();
  
  // Sets up variables for the JSON of the block, and JSON of block plus CSS/JS.
  $json_block = array('page' => $block['content']);
  // Sets up content array so page, css, and js can be added at specific points.
  $json_content = array('page' => $content, 'css' => $css, 'js' => $js);
  
  if(isset($block) && is_array($block) && isset($block['content'])) { 
    if($theme == FALSE) {
      if($format == 'html') {
        print $block['content'];
      }
      elseif($format == 'json') {
        if(isset($_GET['callback'])) {
          $json_callback = $_GET['callback'];
        }
        else {
          $json_callback = '';
        }
        echo $json_callback . '(' . json_encode($json_block) . ');';
      }
			else {
			  print 'Invalid format.';
      }
		}
    else {
      if($format == 'html') {
        print $content;
      }
      elseif($format == 'json') {
        if(isset($_GET['callback'])) {
          $json_callback = $_GET['callback'];
        }
        else {
          $json_callback = '';
        }
        echo $json_callback . '(' . json_encode($json_content) . ');';
      }
			else {
			  print 'Invalid format.';
			}
    }
  }
}
